eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  zipkin:
    # Para integrar con Jaeger
    base-url: http://jaeger:5775/api/traces  # Cambia esto si tu Jaeger está en otra dirección o puerto
  sleuth:
    sampler:
      probability: 1.0

  # Prometheus - Exportación de métricas
  metrics:
    export:
      prometheus:
        enabled: true  # Habilitar la exportación de métricas a Prometheus
        step: 30s  # Intervalo para las métricas

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Exponer los endpoints de Prometheus


#okta:
#  oauth2:
#    issuer: https://dev-33389831.okta.com/oauth2/default
#    audience: api://default    
  
